/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: b44pUm4nfW6C6Fzcbpx1wb
// Component: vg4CkfvsY0cH

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { useScreenVariants as useScreenVariantswYGucrvFIpH5 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: wYGucrvFIpH5/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: b44pUm4nfW6C6Fzcbpx1wb/projectcss
import sty from "./PlasmicProjectContent2.module.css"; // plasmic-import: vg4CkfvsY0cH/css

import PinIconSvgIcon from "./icons/PlasmicIcon__PinIconSvg"; // plasmic-import: V9OvwbGhu1Ay/icon

createPlasmicElementProxy;

export type PlasmicProjectContent2__VariantMembers = {};
export type PlasmicProjectContent2__VariantsArgs = {};
type VariantPropType = keyof PlasmicProjectContent2__VariantsArgs;
export const PlasmicProjectContent2__VariantProps =
  new Array<VariantPropType>();

export type PlasmicProjectContent2__ArgsType = { showMonth?: boolean };
type ArgPropType = keyof PlasmicProjectContent2__ArgsType;
export const PlasmicProjectContent2__ArgProps = new Array<ArgPropType>(
  "showMonth"
);

export type PlasmicProjectContent2__OverridesType = {
  content3?: Flex__<"div">;
  col27?: Flex__<"div">;
  monthContainer4?: Flex__<"div">;
  monthHeading4?: Flex__<"h5">;
  project12?: Flex__<"div">;
  container17?: Flex__<"div">;
  projectImg4?: Flex__<"div">;
  img?: Flex__<typeof PlasmicImg__>;
  col28?: Flex__<"div">;
  projectName4?: Flex__<"h3">;
  projectLoc4?: Flex__<"div">;
  locationIcon4?: Flex__<"svg">;
  locationHeading4?: Flex__<"h5">;
  projectDescriptionContainer4?: Flex__<"div">;
  projectDescription4?: Flex__<"div">;
  projectDetailsContainer4?: Flex__<"div">;
  projectDetails4?: Flex__<"div">;
  kWpContainer4?: Flex__<"div">;
  kWpNumber4?: Flex__<"h3">;
  kWpLabel4?: Flex__<"div">;
  solarFractionContainer4?: Flex__<"div">;
  solarFractionNumber4?: Flex__<"h3">;
  solarFractionLabel4?: Flex__<"div">;
  roiOrSavingsContainer4?: Flex__<"div">;
  roiOrSavingsNumber4?: Flex__<"h3">;
  roiOrSavingsLabel4?: Flex__<"div">;
};

export interface DefaultProjectContent2Props {
  showMonth?: boolean;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicProjectContent2__RenderFunc(props: {
  variants: PlasmicProjectContent2__VariantsArgs;
  args: PlasmicProjectContent2__ArgsType;
  overrides: PlasmicProjectContent2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          showMonth: true
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswYGucrvFIpH5()
  });

  return (
    <div
      data-plasmic-name={"content3"}
      data-plasmic-override={overrides.content3}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.content3
      )}
    >
      <Stack__
        as={"div"}
        data-plasmic-name={"col27"}
        data-plasmic-override={overrides.col27}
        hasGap={true}
        className={classNames(projectcss.all, sty.col27)}
      >
        {(() => {
          try {
            return $props.showMonth;
          } catch (e) {
            if (
              e instanceof TypeError ||
              e?.plasmicType === "PlasmicUndefinedDataError"
            ) {
              return true;
            }
            throw e;
          }
        })() ? (
          <div
            data-plasmic-name={"monthContainer4"}
            data-plasmic-override={overrides.monthContainer4}
            className={classNames(projectcss.all, sty.monthContainer4)}
          >
            <h5
              data-plasmic-name={"monthHeading4"}
              data-plasmic-override={overrides.monthHeading4}
              className={classNames(
                projectcss.all,
                projectcss.h5,
                projectcss.__wab_text,
                sty.monthHeading4
              )}
            >
              {"Month"}
            </h5>
          </div>
        ) : null}
        <div
          data-plasmic-name={"project12"}
          data-plasmic-override={overrides.project12}
          className={classNames(projectcss.all, sty.project12)}
        >
          <div
            data-plasmic-name={"container17"}
            data-plasmic-override={overrides.container17}
            className={classNames(projectcss.all, sty.container17)}
          >
            <div
              data-plasmic-name={"projectImg4"}
              data-plasmic-override={overrides.projectImg4}
              className={classNames(projectcss.all, sty.projectImg4)}
            >
              <PlasmicImg__
                data-plasmic-name={"img"}
                data-plasmic-override={overrides.img}
                alt={""}
                className={classNames(sty.img)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? "245px"
                    : "400px"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={"100%"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"700px"}
                loading={"lazy"}
              />
            </div>
            <div
              data-plasmic-name={"col28"}
              data-plasmic-override={overrides.col28}
              className={classNames(projectcss.all, sty.col28)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__px4Dc)}>
                <div className={classNames(projectcss.all, sty.columns__ml1Fw)}>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__sq8Ju)}
                  >
                    <h3
                      data-plasmic-name={"projectName4"}
                      data-plasmic-override={overrides.projectName4}
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.projectName4
                      )}
                    >
                      {"Project Title"}
                    </h3>
                    <Stack__
                      as={"div"}
                      data-plasmic-name={"projectLoc4"}
                      data-plasmic-override={overrides.projectLoc4}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.projectLoc4)}
                    >
                      <PinIconSvgIcon
                        data-plasmic-name={"locationIcon4"}
                        data-plasmic-override={overrides.locationIcon4}
                        className={classNames(
                          projectcss.all,
                          sty.locationIcon4
                        )}
                        role={"img"}
                      />

                      <h5
                        data-plasmic-name={"locationHeading4"}
                        data-plasmic-override={overrides.locationHeading4}
                        className={classNames(
                          projectcss.all,
                          projectcss.h5,
                          projectcss.__wab_text,
                          sty.locationHeading4
                        )}
                      >
                        {"Project Location"}
                      </h5>
                    </Stack__>
                  </Stack__>
                </div>
              </div>
              <div
                data-plasmic-name={"projectDescriptionContainer4"}
                data-plasmic-override={overrides.projectDescriptionContainer4}
                className={classNames(
                  projectcss.all,
                  sty.projectDescriptionContainer4
                )}
              >
                <div className={classNames(projectcss.all, sty.columns__h0GuJ)}>
                  <div
                    className={classNames(projectcss.all, sty.column__ensJ2)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___5WfaJ
                      )}
                    >
                      <div
                        data-plasmic-name={"projectDescription4"}
                        data-plasmic-override={overrides.projectDescription4}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.projectDescription4
                        )}
                      >
                        {
                          "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Excepteur sint occaecat cupidatat non proident."
                        }
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div
                data-plasmic-name={"projectDetailsContainer4"}
                data-plasmic-override={overrides.projectDetailsContainer4}
                className={classNames(
                  projectcss.all,
                  sty.projectDetailsContainer4
                )}
              >
                <div
                  data-plasmic-name={"projectDetails4"}
                  data-plasmic-override={overrides.projectDetails4}
                  className={classNames(projectcss.all, sty.projectDetails4)}
                >
                  <div
                    data-plasmic-name={"kWpContainer4"}
                    data-plasmic-override={overrides.kWpContainer4}
                    className={classNames(projectcss.all, sty.kWpContainer4)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___9YVj0
                      )}
                    >
                      <h3
                        data-plasmic-name={"kWpNumber4"}
                        data-plasmic-override={overrides.kWpNumber4}
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.kWpNumber4
                        )}
                      >
                        {"0"}
                      </h3>
                      <div
                        data-plasmic-name={"kWpLabel4"}
                        data-plasmic-override={overrides.kWpLabel4}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.kWpLabel4
                        )}
                      >
                        {"Kilowatt Peak"}
                      </div>
                    </Stack__>
                  </div>
                  <div
                    data-plasmic-name={"solarFractionContainer4"}
                    data-plasmic-override={overrides.solarFractionContainer4}
                    className={classNames(
                      projectcss.all,
                      sty.solarFractionContainer4
                    )}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__xrfZ8)}
                    >
                      <h3
                        data-plasmic-name={"solarFractionNumber4"}
                        data-plasmic-override={overrides.solarFractionNumber4}
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.solarFractionNumber4
                        )}
                      >
                        {"0%"}
                      </h3>
                      <div
                        data-plasmic-name={"solarFractionLabel4"}
                        data-plasmic-override={overrides.solarFractionLabel4}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.solarFractionLabel4
                        )}
                      >
                        {"Solar Fraction"}
                      </div>
                    </Stack__>
                  </div>
                  <div
                    data-plasmic-name={"roiOrSavingsContainer4"}
                    data-plasmic-override={overrides.roiOrSavingsContainer4}
                    className={classNames(
                      projectcss.all,
                      sty.roiOrSavingsContainer4
                    )}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__jVkfm)}
                    >
                      <h3
                        data-plasmic-name={"roiOrSavingsNumber4"}
                        data-plasmic-override={overrides.roiOrSavingsNumber4}
                        className={classNames(
                          projectcss.all,
                          projectcss.h3,
                          projectcss.__wab_text,
                          sty.roiOrSavingsNumber4
                        )}
                      >
                        {"0"}
                      </h3>
                      <div
                        data-plasmic-name={"roiOrSavingsLabel4"}
                        data-plasmic-override={overrides.roiOrSavingsLabel4}
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.roiOrSavingsLabel4
                        )}
                      >
                        {"ROI/Savings"}
                      </div>
                    </Stack__>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Stack__>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  content3: [
    "content3",
    "col27",
    "monthContainer4",
    "monthHeading4",
    "project12",
    "container17",
    "projectImg4",
    "img",
    "col28",
    "projectName4",
    "projectLoc4",
    "locationIcon4",
    "locationHeading4",
    "projectDescriptionContainer4",
    "projectDescription4",
    "projectDetailsContainer4",
    "projectDetails4",
    "kWpContainer4",
    "kWpNumber4",
    "kWpLabel4",
    "solarFractionContainer4",
    "solarFractionNumber4",
    "solarFractionLabel4",
    "roiOrSavingsContainer4",
    "roiOrSavingsNumber4",
    "roiOrSavingsLabel4"
  ],
  col27: [
    "col27",
    "monthContainer4",
    "monthHeading4",
    "project12",
    "container17",
    "projectImg4",
    "img",
    "col28",
    "projectName4",
    "projectLoc4",
    "locationIcon4",
    "locationHeading4",
    "projectDescriptionContainer4",
    "projectDescription4",
    "projectDetailsContainer4",
    "projectDetails4",
    "kWpContainer4",
    "kWpNumber4",
    "kWpLabel4",
    "solarFractionContainer4",
    "solarFractionNumber4",
    "solarFractionLabel4",
    "roiOrSavingsContainer4",
    "roiOrSavingsNumber4",
    "roiOrSavingsLabel4"
  ],
  monthContainer4: ["monthContainer4", "monthHeading4"],
  monthHeading4: ["monthHeading4"],
  project12: [
    "project12",
    "container17",
    "projectImg4",
    "img",
    "col28",
    "projectName4",
    "projectLoc4",
    "locationIcon4",
    "locationHeading4",
    "projectDescriptionContainer4",
    "projectDescription4",
    "projectDetailsContainer4",
    "projectDetails4",
    "kWpContainer4",
    "kWpNumber4",
    "kWpLabel4",
    "solarFractionContainer4",
    "solarFractionNumber4",
    "solarFractionLabel4",
    "roiOrSavingsContainer4",
    "roiOrSavingsNumber4",
    "roiOrSavingsLabel4"
  ],
  container17: [
    "container17",
    "projectImg4",
    "img",
    "col28",
    "projectName4",
    "projectLoc4",
    "locationIcon4",
    "locationHeading4",
    "projectDescriptionContainer4",
    "projectDescription4",
    "projectDetailsContainer4",
    "projectDetails4",
    "kWpContainer4",
    "kWpNumber4",
    "kWpLabel4",
    "solarFractionContainer4",
    "solarFractionNumber4",
    "solarFractionLabel4",
    "roiOrSavingsContainer4",
    "roiOrSavingsNumber4",
    "roiOrSavingsLabel4"
  ],
  projectImg4: ["projectImg4", "img"],
  img: ["img"],
  col28: [
    "col28",
    "projectName4",
    "projectLoc4",
    "locationIcon4",
    "locationHeading4",
    "projectDescriptionContainer4",
    "projectDescription4",
    "projectDetailsContainer4",
    "projectDetails4",
    "kWpContainer4",
    "kWpNumber4",
    "kWpLabel4",
    "solarFractionContainer4",
    "solarFractionNumber4",
    "solarFractionLabel4",
    "roiOrSavingsContainer4",
    "roiOrSavingsNumber4",
    "roiOrSavingsLabel4"
  ],
  projectName4: ["projectName4"],
  projectLoc4: ["projectLoc4", "locationIcon4", "locationHeading4"],
  locationIcon4: ["locationIcon4"],
  locationHeading4: ["locationHeading4"],
  projectDescriptionContainer4: [
    "projectDescriptionContainer4",
    "projectDescription4"
  ],
  projectDescription4: ["projectDescription4"],
  projectDetailsContainer4: [
    "projectDetailsContainer4",
    "projectDetails4",
    "kWpContainer4",
    "kWpNumber4",
    "kWpLabel4",
    "solarFractionContainer4",
    "solarFractionNumber4",
    "solarFractionLabel4",
    "roiOrSavingsContainer4",
    "roiOrSavingsNumber4",
    "roiOrSavingsLabel4"
  ],
  projectDetails4: [
    "projectDetails4",
    "kWpContainer4",
    "kWpNumber4",
    "kWpLabel4",
    "solarFractionContainer4",
    "solarFractionNumber4",
    "solarFractionLabel4",
    "roiOrSavingsContainer4",
    "roiOrSavingsNumber4",
    "roiOrSavingsLabel4"
  ],
  kWpContainer4: ["kWpContainer4", "kWpNumber4", "kWpLabel4"],
  kWpNumber4: ["kWpNumber4"],
  kWpLabel4: ["kWpLabel4"],
  solarFractionContainer4: [
    "solarFractionContainer4",
    "solarFractionNumber4",
    "solarFractionLabel4"
  ],
  solarFractionNumber4: ["solarFractionNumber4"],
  solarFractionLabel4: ["solarFractionLabel4"],
  roiOrSavingsContainer4: [
    "roiOrSavingsContainer4",
    "roiOrSavingsNumber4",
    "roiOrSavingsLabel4"
  ],
  roiOrSavingsNumber4: ["roiOrSavingsNumber4"],
  roiOrSavingsLabel4: ["roiOrSavingsLabel4"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  content3: "div";
  col27: "div";
  monthContainer4: "div";
  monthHeading4: "h5";
  project12: "div";
  container17: "div";
  projectImg4: "div";
  img: typeof PlasmicImg__;
  col28: "div";
  projectName4: "h3";
  projectLoc4: "div";
  locationIcon4: "svg";
  locationHeading4: "h5";
  projectDescriptionContainer4: "div";
  projectDescription4: "div";
  projectDetailsContainer4: "div";
  projectDetails4: "div";
  kWpContainer4: "div";
  kWpNumber4: "h3";
  kWpLabel4: "div";
  solarFractionContainer4: "div";
  solarFractionNumber4: "h3";
  solarFractionLabel4: "div";
  roiOrSavingsContainer4: "div";
  roiOrSavingsNumber4: "h3";
  roiOrSavingsLabel4: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProjectContent2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProjectContent2__VariantsArgs;
    args?: PlasmicProjectContent2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProjectContent2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicProjectContent2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicProjectContent2__ArgProps,
          internalVariantPropNames: PlasmicProjectContent2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicProjectContent2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "content3") {
    func.displayName = "PlasmicProjectContent2";
  } else {
    func.displayName = `PlasmicProjectContent2.${nodeName}`;
  }
  return func;
}

export const PlasmicProjectContent2 = Object.assign(
  // Top-level PlasmicProjectContent2 renders the root element
  makeNodeComponent("content3"),
  {
    // Helper components rendering sub-elements
    col27: makeNodeComponent("col27"),
    monthContainer4: makeNodeComponent("monthContainer4"),
    monthHeading4: makeNodeComponent("monthHeading4"),
    project12: makeNodeComponent("project12"),
    container17: makeNodeComponent("container17"),
    projectImg4: makeNodeComponent("projectImg4"),
    img: makeNodeComponent("img"),
    col28: makeNodeComponent("col28"),
    projectName4: makeNodeComponent("projectName4"),
    projectLoc4: makeNodeComponent("projectLoc4"),
    locationIcon4: makeNodeComponent("locationIcon4"),
    locationHeading4: makeNodeComponent("locationHeading4"),
    projectDescriptionContainer4: makeNodeComponent(
      "projectDescriptionContainer4"
    ),
    projectDescription4: makeNodeComponent("projectDescription4"),
    projectDetailsContainer4: makeNodeComponent("projectDetailsContainer4"),
    projectDetails4: makeNodeComponent("projectDetails4"),
    kWpContainer4: makeNodeComponent("kWpContainer4"),
    kWpNumber4: makeNodeComponent("kWpNumber4"),
    kWpLabel4: makeNodeComponent("kWpLabel4"),
    solarFractionContainer4: makeNodeComponent("solarFractionContainer4"),
    solarFractionNumber4: makeNodeComponent("solarFractionNumber4"),
    solarFractionLabel4: makeNodeComponent("solarFractionLabel4"),
    roiOrSavingsContainer4: makeNodeComponent("roiOrSavingsContainer4"),
    roiOrSavingsNumber4: makeNodeComponent("roiOrSavingsNumber4"),
    roiOrSavingsLabel4: makeNodeComponent("roiOrSavingsLabel4"),

    // Metadata about props expected for PlasmicProjectContent2
    internalVariantProps: PlasmicProjectContent2__VariantProps,
    internalArgProps: PlasmicProjectContent2__ArgProps
  }
);

export default PlasmicProjectContent2;
/* prettier-ignore-end */
