/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: b44pUm4nfW6C6Fzcbpx1wb
// Component: SkOoRQSJN2-t

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: b44pUm4nfW6C6Fzcbpx1wb/projectcss
import sty from "./PlasmicYearDivider.module.css"; // plasmic-import: SkOoRQSJN2-t/css

import Line2Icon from "./icons/PlasmicIcon__Line2"; // plasmic-import: Np22ccQ3Lsvm/icon

createPlasmicElementProxy;

export type PlasmicYearDivider__VariantMembers = {};
export type PlasmicYearDivider__VariantsArgs = {};
type VariantPropType = keyof PlasmicYearDivider__VariantsArgs;
export const PlasmicYearDivider__VariantProps = new Array<VariantPropType>();

export type PlasmicYearDivider__ArgsType = {};
type ArgPropType = keyof PlasmicYearDivider__ArgsType;
export const PlasmicYearDivider__ArgProps = new Array<ArgPropType>();

export type PlasmicYearDivider__OverridesType = {
  yearDivider?: Flex__<"div">;
  yearHeading?: Flex__<"h2">;
  divider?: Flex__<"svg">;
};

export interface DefaultYearDividerProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicYearDivider__RenderFunc(props: {
  variants: PlasmicYearDivider__VariantsArgs;
  args: PlasmicYearDivider__ArgsType;
  overrides: PlasmicYearDivider__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"yearDivider"}
      data-plasmic-override={overrides.yearDivider}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.yearDivider
      )}
    >
      <h2
        data-plasmic-name={"yearHeading"}
        data-plasmic-override={overrides.yearHeading}
        className={classNames(
          projectcss.all,
          projectcss.h2,
          projectcss.__wab_text,
          sty.yearHeading
        )}
        id={"1"}
      >
        {"2024"}
      </h2>
      <Line2Icon
        data-plasmic-name={"divider"}
        data-plasmic-override={overrides.divider}
        className={classNames(projectcss.all, sty.divider)}
        role={"img"}
      />
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  yearDivider: ["yearDivider", "yearHeading", "divider"],
  yearHeading: ["yearHeading"],
  divider: ["divider"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  yearDivider: "div";
  yearHeading: "h2";
  divider: "svg";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicYearDivider__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicYearDivider__VariantsArgs;
    args?: PlasmicYearDivider__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicYearDivider__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicYearDivider__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicYearDivider__ArgProps,
          internalVariantPropNames: PlasmicYearDivider__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicYearDivider__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "yearDivider") {
    func.displayName = "PlasmicYearDivider";
  } else {
    func.displayName = `PlasmicYearDivider.${nodeName}`;
  }
  return func;
}

export const PlasmicYearDivider = Object.assign(
  // Top-level PlasmicYearDivider renders the root element
  makeNodeComponent("yearDivider"),
  {
    // Helper components rendering sub-elements
    yearHeading: makeNodeComponent("yearHeading"),
    divider: makeNodeComponent("divider"),

    // Metadata about props expected for PlasmicYearDivider
    internalVariantProps: PlasmicYearDivider__VariantProps,
    internalArgProps: PlasmicYearDivider__ArgProps
  }
);

export default PlasmicYearDivider;
/* prettier-ignore-end */
