/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: b44pUm4nfW6C6Fzcbpx1wb
// Component: WJteRYGTKFcv

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";

import { useScreenVariants as useScreenVariantswYGucrvFIpH5 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: wYGucrvFIpH5/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: b44pUm4nfW6C6Fzcbpx1wb/projectcss
import sty from "./PlasmicSolutions.module.css"; // plasmic-import: WJteRYGTKFcv/css

import ArrowRightIcon from "./icons/PlasmicIcon__ArrowRight"; // plasmic-import: bjpoZj6j_N3c/icon
import CheckCircleFill1SvgIcon from "./icons/PlasmicIcon__CheckCircleFill1Svg"; // plasmic-import: nhxw9VH6HLgH/icon
import SunFillSvgIcon from "./icons/PlasmicIcon__SunFillSvg"; // plasmic-import: chufAfZw529U/icon
import GeoAltFill1SvgIcon from "./icons/PlasmicIcon__GeoAltFill1Svg"; // plasmic-import: N661ASTPOBbP/icon
import EnvelopeFill1SvgIcon from "./icons/PlasmicIcon__EnvelopeFill1Svg"; // plasmic-import: K3EMqprSG4Sx/icon
import Linkedin2SvgIcon from "./icons/PlasmicIcon__Linkedin2Svg"; // plasmic-import: JSoyWAqD2o0A/icon
import Facebook2SvgIcon from "./icons/PlasmicIcon__Facebook2Svg"; // plasmic-import: 3taEzhm_7HIU/icon
import ArrowUpRightCircleFill2SvgIcon from "./icons/PlasmicIcon__ArrowUpRightCircleFill2Svg"; // plasmic-import: QV28IsMmBIyd/icon

createPlasmicElementProxy;

export type PlasmicSolutions__VariantMembers = {};
export type PlasmicSolutions__VariantsArgs = {};
type VariantPropType = keyof PlasmicSolutions__VariantsArgs;
export const PlasmicSolutions__VariantProps = new Array<VariantPropType>();

export type PlasmicSolutions__ArgsType = {};
type ArgPropType = keyof PlasmicSolutions__ArgsType;
export const PlasmicSolutions__ArgProps = new Array<ArgPropType>();

export type PlasmicSolutions__OverridesType = {
  solutionPage?: Flex__<"div">;
  landingPage?: Flex__<"div">;
  heading?: Flex__<"div">;
  image?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  logo7?: Flex__<"a"> & Partial<LinkProps>;
  solution4?: Flex__<"a"> & Partial<LinkProps>;
  logo8?: Flex__<"a"> & Partial<LinkProps>;
  value?: Flex__<"div">;
  offers?: Flex__<"div">;
  offer?: Flex__<"div">;
  offer2?: Flex__<"div">;
  offer3?: Flex__<"div">;
  offer4?: Flex__<"div">;
  offer5?: Flex__<"div">;
  offer6?: Flex__<"div">;
  financingOptions?: Flex__<"div">;
  options?: Flex__<"div">;
  footer?: Flex__<"footer">;
  section5?: Flex__<"div">;
  brandLogo3?: Flex__<"div">;
  section6?: Flex__<"div">;
  h4?: Flex__<"h4">;
  whereToFindUs3?: Flex__<"div">;
  connectWithUs4?: Flex__<"div">;
  getSolar3?: Flex__<"div">;
};

export interface DefaultSolutionsProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSolutions__RenderFunc(props: {
  variants: PlasmicSolutions__VariantsArgs;
  args: PlasmicSolutions__ArgsType;
  overrides: PlasmicSolutions__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "variable",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantswYGucrvFIpH5()
  });

  return (
    <React.Fragment>
      <Head></Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"solutionPage"}
          data-plasmic-override={overrides.solutionPage}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.solutionPage
          )}
          id={``}
        >
          <div
            data-plasmic-name={"landingPage"}
            data-plasmic-override={overrides.landingPage}
            className={classNames(projectcss.all, sty.landingPage)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__eTu68)}>
              <div
                data-plasmic-name={"heading"}
                data-plasmic-override={overrides.heading}
                className={classNames(projectcss.all, sty.heading)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__vGnBg)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__jW8Gs)}
                  >
                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1___5CqxJ
                      )}
                    >
                      {hasVariant(globalVariants, "screen", "mobileOnly") ? (
                        <React.Fragment>
                          <React.Fragment>
                            {"Lighting pathways to sustainability:\n"}
                          </React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {"Excell Energy\u2019s Focus"}
                          </span>
                        </React.Fragment>
                      ) : (
                        <React.Fragment>
                          <React.Fragment>
                            {"Trusted Sustainability: \n"}
                          </React.Fragment>
                          <span
                            className={
                              "plasmic_default__all plasmic_default__span"
                            }
                            style={{ fontWeight: 700 }}
                          >
                            {"Years of Solar Energy Solutions"}
                          </span>
                        </React.Fragment>
                      )}
                    </h1>
                  </div>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__vdWv)}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pl1Vj
                      )}
                    >
                      {
                        "Ready to make the switch to solar? Let our experts guide you in finding the best energy solution for your business or industry."
                      }
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"image"}
                    data-plasmic-override={overrides.image}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.image)}
                  />
                </Stack__>
              </div>
            </div>
            <NavigationBar
              data-plasmic-name={"navigationBar"}
              data-plasmic-override={overrides.navigationBar}
              brand={
                <PlasmicLink__
                  data-plasmic-name={"logo7"}
                  data-plasmic-override={overrides.logo7}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.logo7
                  )}
                  component={Link}
                  href={"#"}
                  platform={"nextjs"}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__asNo7)}
                    displayHeight={"40px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"298px"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    src={{
                      src: "/plasmic/copy_of_excell_website_final/images/layer2.svg",
                      fullWidth: 220.00169372558594,
                      fullHeight: 80.00094604492188,
                      aspectRatio: 2.75
                    }}
                  />
                </PlasmicLink__>
              }
              className={classNames("__wab_instance", sty.navigationBar)}
              closeButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___9EhWq)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"32px"}
                  src={{
                    src: "/plasmic/copy_of_excell_website_final/images/xLgSvg2.svg",
                    fullWidth: 24,
                    fullHeight: 25,
                    aspectRatio: 0.96
                  }}
                />
              }
              forceOpenMenu={
                hasVariant(globalVariants, "screen", "mobileOnly")
                  ? true
                  : false
              }
              itemsGap={
                hasVariant(globalVariants, "screen", "mobileOnly") ? 48 : 48
              }
              menuItems={
                <React.Fragment>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___4Stll
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    {"Home"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    data-plasmic-name={"solution4"}
                    data-plasmic-override={overrides.solution4}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.solution4
                    )}
                    component={Link}
                    href={`/solutions`}
                    platform={"nextjs"}
                  >
                    {"Solution"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__g2UZd
                    )}
                    component={Link}
                    href={`/projects`}
                    platform={"nextjs"}
                  >
                    {"Projects"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    data-plasmic-name={"logo8"}
                    data-plasmic-override={overrides.logo8}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.logo8
                    )}
                    component={Link}
                    href={`/`}
                    platform={"nextjs"}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__yz3A)}
                      displayHeight={"64px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"298px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={{
                        src: "/plasmic/copy_of_excell_website_final/images/excellVerticalLogoPng.png",
                        fullWidth: 987,
                        fullHeight: 1002,
                        aspectRatio: undefined
                      }}
                    />
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__vwHnH
                    )}
                    component={Link}
                    href={`/about`}
                    platform={"nextjs"}
                  >
                    {"About"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__xIeP1
                    )}
                    component={Link}
                    href={`/learn`}
                    platform={"nextjs"}
                  >
                    {"Learn"}
                  </PlasmicLink__>
                  <PlasmicLink__
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___9HsP9
                    )}
                    component={Link}
                    href={`/contact`}
                    platform={"nextjs"}
                  >
                    {"Contact Us"}
                  </PlasmicLink__>
                </React.Fragment>
              }
              openButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__vewGy)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"32px"}
                  src={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? {
                          src: "/plasmic/copy_of_excell_website_final/images/hamburgerMenuSvg.svg",
                          fullWidth: 24,
                          fullHeight: 25,
                          aspectRatio: 0.96
                        }
                      : undefined
                  }
                  width={"32"}
                />
              }
              responsiveBreakpoint={768}
            />
          </div>
          <Stack__
            as={"div"}
            data-plasmic-name={"value"}
            data-plasmic-override={overrides.value}
            hasGap={true}
            className={classNames(projectcss.all, sty.value)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__j4Ilk)}
            >
              <div className={classNames(projectcss.all, sty.column__flcQd)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img___3DjrX)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "auto"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/copy_of_excell_website_final/images/environmentalEngineersWorkingTogetherJpg.jpg",
                    fullWidth: 5773,
                    fullHeight: 3848,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__zR1P)}
              >
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__meSLe
                  )}
                >
                  {"Commercial & Industrial Solar That Works for You"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mkCdt
                  )}
                >
                  {
                    "Save money. Help the planet. Stand out. Our solar solutions are tailored for your company\u2019s growth and long-term resilience.\r"
                  }
                </div>
                <Stack__
                  as={PlasmicLink__}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__jCz6T
                  )}
                  component={Link}
                  href={`/projects`}
                  platform={"nextjs"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__mkjbm
                    )}
                  >
                    {"See our Projects"}
                  </div>
                  <ArrowRightIcon
                    className={classNames(projectcss.all, sty.svg__z2Cby)}
                    role={"img"}
                  />
                </Stack__>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"offers"}
            data-plasmic-override={overrides.offers}
            hasGap={true}
            className={classNames(projectcss.all, sty.offers)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__wiO)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___6XW4O)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__xCdBn)}>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__lj1Sk
                    )}
                  >
                    {"What more can we offer?"}
                  </h1>
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__ktmyI)}
                >
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"offer"}
                    data-plasmic-override={overrides.offer}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.offer)}
                  >
                    <CheckCircleFill1SvgIcon
                      className={classNames(projectcss.all, sty.svg__miosz)}
                      role={"img"}
                    />

                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__tlnT0
                      )}
                    >
                      {"Load and Energy Study"}
                    </h1>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"offer2"}
                    data-plasmic-override={overrides.offer2}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.offer2)}
                  >
                    <CheckCircleFill1SvgIcon
                      className={classNames(projectcss.all, sty.svg__wvxsr)}
                      role={"img"}
                    />

                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__jUDll
                      )}
                    >
                      {"Optimized Design"}
                    </h1>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"offer3"}
                    data-plasmic-override={overrides.offer3}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.offer3)}
                  >
                    <CheckCircleFill1SvgIcon
                      className={classNames(projectcss.all, sty.svg__xwwZo)}
                      role={"img"}
                    />

                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1___0RLab
                      )}
                    >
                      {"Best-in-class Components "}
                    </h1>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"offer4"}
                    data-plasmic-override={overrides.offer4}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.offer4)}
                  >
                    <CheckCircleFill1SvgIcon
                      className={classNames(projectcss.all, sty.svg__zbXKw)}
                      role={"img"}
                    />

                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__nd6Bv
                      )}
                    >
                      {"Flexible Payment Options"}
                    </h1>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"offer5"}
                    data-plasmic-override={overrides.offer5}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.offer5)}
                  >
                    <CheckCircleFill1SvgIcon
                      className={classNames(projectcss.all, sty.svg__hmaoq)}
                      role={"img"}
                    />

                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__szkkf
                      )}
                    >
                      {"Smart Monitoring"}
                    </h1>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    data-plasmic-name={"offer6"}
                    data-plasmic-override={overrides.offer6}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.offer6)}
                  >
                    <CheckCircleFill1SvgIcon
                      className={classNames(projectcss.all, sty.svg___4Wpsp)}
                      role={"img"}
                    />

                    <h1
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1__kx8KM
                      )}
                    >
                      {"Long-term Warranty"}
                    </h1>
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"financingOptions"}
            data-plasmic-override={overrides.financingOptions}
            hasGap={true}
            className={classNames(projectcss.all, sty.financingOptions)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___8HcCr)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__cRj5O)}
              >
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__rbjwP
                  )}
                >
                  {"Our Financing Options"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__naTjj
                  )}
                >
                  {
                    "Our ultimate goal is to foster social impact through solutions that drive innovation, sustainable development, and environmental stewardship in the Philippines. We do this by ensuring cost efficiency alongside cutting-edge technologies, one solar rooftop at a time."
                  }
                </div>
                <Stack__
                  as={PlasmicLink__}
                  hasGap={true}
                  className={classNames(
                    projectcss.all,
                    projectcss.a,
                    sty.link__fh0Go
                  )}
                  component={Link}
                  href={`/get-solar`}
                  platform={"nextjs"}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___5JkVk
                    )}
                  >
                    {"Get Started"}
                  </div>
                </Stack__>
              </Stack__>
              <div className={classNames(projectcss.all, sty.column__hqjnB)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__mIYjR)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "auto"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  loading={"lazy"}
                  src={{
                    src: "/plasmic/copy_of_excell_website_final/images/behindExcellImage.jpg",
                    fullWidth: 6048,
                    fullHeight: 4024,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </Stack__>
          </Stack__>
          <Stack__
            as={"div"}
            data-plasmic-name={"options"}
            data-plasmic-override={overrides.options}
            hasGap={true}
            className={classNames(projectcss.all, sty.options)}
          >
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__r8F5Q)}
            >
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___3EiS)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__nDqHi)}>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__aU9O)}
                  >
                    <SunFillSvgIcon
                      className={classNames(projectcss.all, sty.svg___9Rly8)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___48Dhj
                      )}
                    >
                      {"Option 1"}
                    </div>
                  </Stack__>
                </div>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1___40BEr
                  )}
                >
                  {"Turnkey Purchase"}
                </h1>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__zLdy8)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__sxJzR)}
                  >
                    <CheckCircleFill1SvgIcon
                      className={classNames(projectcss.all, sty.svg___878Tn)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qi4Tv
                      )}
                    >
                      {"Pay upfront or by milestone\r"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__syx2L)}
                  >
                    <CheckCircleFill1SvgIcon
                      className={classNames(projectcss.all, sty.svg__jUndp)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fXeo0
                      )}
                    >
                      {"One-year warranty, semi-annual service\r"}
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column___6V9Mn)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__wvlO)}>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__h5GHc)}
                  >
                    <SunFillSvgIcon
                      className={classNames(projectcss.all, sty.svg___01PRr)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pNxPk
                      )}
                    >
                      {"Option 2"}
                    </div>
                  </Stack__>
                </div>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1__rhYt
                  )}
                >
                  {"Build - Operate - Transfer (BOT)"}
                </h1>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__qCAet)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___1YbAk)}
                  >
                    <CheckCircleFill1SvgIcon
                      className={classNames(projectcss.all, sty.svg__t8L9J)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__aXs8H
                      )}
                    >
                      {"Zero CAPEX, fixed monthly fee"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__t21Zm)}
                  >
                    <CheckCircleFill1SvgIcon
                      className={classNames(projectcss.all, sty.svg__g7VBj)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__j0UQa
                      )}
                    >
                      {"System transferred after term\r"}
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__dZ1)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__vz5Zo)}>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__fPiEe)}
                  >
                    <SunFillSvgIcon
                      className={classNames(projectcss.all, sty.svg__vZsSq)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xaEaR
                      )}
                    >
                      {"Option 3"}
                    </div>
                  </Stack__>
                </div>
                <h1
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1___7QQnC
                  )}
                >
                  {"Power Purchase Agreement (PPA)"}
                </h1>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__spsg)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__gilkx)}
                  >
                    <CheckCircleFill1SvgIcon
                      className={classNames(projectcss.all, sty.svg__b9X5U)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1FV7C
                      )}
                    >
                      {"Pay per kWh usage\r"}
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__l6H8T)}
                  >
                    <CheckCircleFill1SvgIcon
                      className={classNames(projectcss.all, sty.svg__btDsR)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mhcCe
                      )}
                    >
                      {"Long-term savings, no upfront cost\r"}
                    </div>
                  </Stack__>
                </Stack__>
              </Stack__>
            </Stack__>
          </Stack__>
          <footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames(projectcss.all, sty.footer)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__mum1Q)}>
              <div
                data-plasmic-name={"section5"}
                data-plasmic-override={overrides.section5}
                className={classNames(projectcss.all, sty.section5)}
              >
                <div
                  data-plasmic-name={"brandLogo3"}
                  data-plasmic-override={overrides.brandLogo3}
                  className={classNames(projectcss.all, sty.brandLogo3)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__cafu)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "50%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"240px"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/copy_of_excell_website_final/images/excellHorizontalLogoPng.png",
                      fullWidth: 2001,
                      fullHeight: 706,
                      aspectRatio: undefined
                    }}
                  />

                  <div
                    data-plasmic-name={"section6"}
                    data-plasmic-override={overrides.section6}
                    className={classNames(projectcss.all, sty.section6)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__dxmuy)}
                    >
                      <Stack__
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__mRuCv
                        )}
                      >
                        <h4
                          data-plasmic-name={"h4"}
                          data-plasmic-override={overrides.h4}
                          className={classNames(
                            projectcss.all,
                            projectcss.h4,
                            projectcss.__wab_text,
                            sty.h4
                          )}
                        >
                          {"Lighting pathways to sustainability"}
                        </h4>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__oLgp
                          )}
                        >
                          {
                            "We empower industries by providing innovative, financial and technological solutions to energy problems.\n\n\r\nWe specialize in providing end-to-end solar solutions starting from expert energy assessment, to quality equipment and workmanship, and with lifetime support and maintenance."
                          }
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__rAPa
                          )}
                        >
                          {
                            "\u00a9 Copyright 2025 Excell Energy and Powergen Inc. All rights reserved."
                          }
                        </div>
                      </Stack__>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.column__rr3Ld)}
                    >
                      <div
                        data-plasmic-name={"whereToFindUs3"}
                        data-plasmic-override={overrides.whereToFindUs3}
                        className={classNames(
                          projectcss.all,
                          sty.whereToFindUs3
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__goUBd
                          )}
                        >
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__j0Gxg
                            )}
                          >
                            {"Where to find us?"}
                          </h5>
                        </div>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__aXiWk
                          )}
                        >
                          <GeoAltFill1SvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__pXf4D
                            )}
                            role={"img"}
                          />

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__gLu70
                            )}
                          >
                            {
                              "Unit 2618, 26th flr, High Street South Corporate Plaza Tower 1 26th St, cor 9th Ave, 1634 Taguig, Philippines"
                            }
                          </div>
                        </Stack__>
                      </div>
                      <div
                        data-plasmic-name={"connectWithUs4"}
                        data-plasmic-override={overrides.connectWithUs4}
                        className={classNames(
                          projectcss.all,
                          sty.connectWithUs4
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__kwYs
                          )}
                        >
                          <h5
                            className={classNames(
                              projectcss.all,
                              projectcss.h5,
                              projectcss.__wab_text,
                              sty.h5__cAn36
                            )}
                          >
                            {"Connect with us!"}
                          </h5>
                        </div>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ixQ
                          )}
                        >
                          <EnvelopeFill1SvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__qraBf
                            )}
                            role={"img"}
                          />

                          <PlasmicLink__
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link___3Qdy
                            )}
                            component={Link}
                            href={"https://www.plasmic.app/"}
                            platform={"nextjs"}
                          >
                            {"solutions@excell.energy"}
                          </PlasmicLink__>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__kgBo
                          )}
                        >
                          <Linkedin2SvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___4KLac
                            )}
                            role={"img"}
                          />

                          <PlasmicLink__
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link__ds5Vv
                            )}
                            component={Link}
                            href={"https://www.plasmic.app/"}
                            platform={"nextjs"}
                          >
                            {"Excell Energy and PowerGen Corp."}
                          </PlasmicLink__>
                        </Stack__>
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__c6XLq
                          )}
                        >
                          <Facebook2SvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__eAhgZ
                            )}
                            role={"img"}
                          />

                          <PlasmicLink__
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link__qmh9G
                            )}
                            component={Link}
                            href={"https://www.plasmic.app/"}
                            platform={"nextjs"}
                          >
                            {"Excell Energy and PowerGen Corp."}
                          </PlasmicLink__>
                        </Stack__>
                      </div>
                      <div
                        data-plasmic-name={"getSolar3"}
                        data-plasmic-override={overrides.getSolar3}
                        className={classNames(projectcss.all, sty.getSolar3)}
                      >
                        <Stack__
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___6HcsA
                          )}
                        >
                          <Stack__
                            as={PlasmicLink__}
                            hasGap={true}
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              sty.link__j3NAy
                            )}
                            component={Link}
                            href={`/get-solar`}
                            platform={"nextjs"}
                          >
                            <h5
                              className={classNames(
                                projectcss.all,
                                projectcss.h5,
                                projectcss.__wab_text,
                                sty.h5___7N2T8
                              )}
                            >
                              {"Get Solar"}
                            </h5>
                            <ArrowUpRightCircleFill2SvgIcon
                              className={classNames(
                                projectcss.all,
                                sty.svg__vUbQu
                              )}
                              role={"img"}
                            />
                          </Stack__>
                        </Stack__>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </footer>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  solutionPage: [
    "solutionPage",
    "landingPage",
    "heading",
    "image",
    "navigationBar",
    "logo7",
    "solution4",
    "logo8",
    "value",
    "offers",
    "offer",
    "offer2",
    "offer3",
    "offer4",
    "offer5",
    "offer6",
    "financingOptions",
    "options",
    "footer",
    "section5",
    "brandLogo3",
    "section6",
    "h4",
    "whereToFindUs3",
    "connectWithUs4",
    "getSolar3"
  ],
  landingPage: [
    "landingPage",
    "heading",
    "image",
    "navigationBar",
    "logo7",
    "solution4",
    "logo8"
  ],
  heading: ["heading", "image"],
  image: ["image"],
  navigationBar: ["navigationBar", "logo7", "solution4", "logo8"],
  logo7: ["logo7"],
  solution4: ["solution4"],
  logo8: ["logo8"],
  value: ["value"],
  offers: ["offers", "offer", "offer2", "offer3", "offer4", "offer5", "offer6"],
  offer: ["offer"],
  offer2: ["offer2"],
  offer3: ["offer3"],
  offer4: ["offer4"],
  offer5: ["offer5"],
  offer6: ["offer6"],
  financingOptions: ["financingOptions"],
  options: ["options"],
  footer: [
    "footer",
    "section5",
    "brandLogo3",
    "section6",
    "h4",
    "whereToFindUs3",
    "connectWithUs4",
    "getSolar3"
  ],
  section5: [
    "section5",
    "brandLogo3",
    "section6",
    "h4",
    "whereToFindUs3",
    "connectWithUs4",
    "getSolar3"
  ],
  brandLogo3: [
    "brandLogo3",
    "section6",
    "h4",
    "whereToFindUs3",
    "connectWithUs4",
    "getSolar3"
  ],
  section6: ["section6", "h4", "whereToFindUs3", "connectWithUs4", "getSolar3"],
  h4: ["h4"],
  whereToFindUs3: ["whereToFindUs3"],
  connectWithUs4: ["connectWithUs4"],
  getSolar3: ["getSolar3"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  solutionPage: "div";
  landingPage: "div";
  heading: "div";
  image: "div";
  navigationBar: typeof NavigationBar;
  logo7: "a";
  solution4: "a";
  logo8: "a";
  value: "div";
  offers: "div";
  offer: "div";
  offer2: "div";
  offer3: "div";
  offer4: "div";
  offer5: "div";
  offer6: "div";
  financingOptions: "div";
  options: "div";
  footer: "footer";
  section5: "div";
  brandLogo3: "div";
  section6: "div";
  h4: "h4";
  whereToFindUs3: "div";
  connectWithUs4: "div";
  getSolar3: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSolutions__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSolutions__VariantsArgs;
    args?: PlasmicSolutions__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSolutions__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSolutions__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSolutions__ArgProps,
          internalVariantPropNames: PlasmicSolutions__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSolutions__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "solutionPage") {
    func.displayName = "PlasmicSolutions";
  } else {
    func.displayName = `PlasmicSolutions.${nodeName}`;
  }
  return func;
}

export const PlasmicSolutions = Object.assign(
  // Top-level PlasmicSolutions renders the root element
  makeNodeComponent("solutionPage"),
  {
    // Helper components rendering sub-elements
    landingPage: makeNodeComponent("landingPage"),
    heading: makeNodeComponent("heading"),
    image: makeNodeComponent("image"),
    navigationBar: makeNodeComponent("navigationBar"),
    logo7: makeNodeComponent("logo7"),
    solution4: makeNodeComponent("solution4"),
    logo8: makeNodeComponent("logo8"),
    value: makeNodeComponent("value"),
    offers: makeNodeComponent("offers"),
    offer: makeNodeComponent("offer"),
    offer2: makeNodeComponent("offer2"),
    offer3: makeNodeComponent("offer3"),
    offer4: makeNodeComponent("offer4"),
    offer5: makeNodeComponent("offer5"),
    offer6: makeNodeComponent("offer6"),
    financingOptions: makeNodeComponent("financingOptions"),
    options: makeNodeComponent("options"),
    footer: makeNodeComponent("footer"),
    section5: makeNodeComponent("section5"),
    brandLogo3: makeNodeComponent("brandLogo3"),
    section6: makeNodeComponent("section6"),
    h4: makeNodeComponent("h4"),
    whereToFindUs3: makeNodeComponent("whereToFindUs3"),
    connectWithUs4: makeNodeComponent("connectWithUs4"),
    getSolar3: makeNodeComponent("getSolar3"),

    // Metadata about props expected for PlasmicSolutions
    internalVariantProps: PlasmicSolutions__VariantProps,
    internalArgProps: PlasmicSolutions__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicSolutions;
/* prettier-ignore-end */
